data:
  header: true
  filename: data.csv
#schematics:
#  Type of building (reference to datafile): file.schematic
#blocks:
#  Type of building (reference to datafile): Name of Material (like ANVIL, for example)