name: WorldBuilder
version: 1.0-SNAPSHOT
main: plugin.PluginManager
description: Spawn game objects across the map
commands:
  placebuildings:
    description: Place buildings according to Minecraft coordinates from data-file
    usage: Type /placebuildings
  availablebuildings:
    description: Show available blocks and schematics that can be placed
    usage: Type /availablebuildings