name: BlockSpawner
version: 0.2
main: plugin.CommandManager
description: Spawn game objects across the map
commands:
  placeblocks:
    aliases: [p]
    description: Place wooden blocks according to set coordinates
    usage: Type /placeblocks
  testplacement:
    aliases: [c]
    description: Place wooden blocks next to the players location
    usage: Type /testplacement
  testschematic:
    aliases: [s]
    description: Place a schematic in the map
    usage: Type /testschematic