name: BlockSpawner
version: 0.2
main: plugin.CommandManager
description: Spawn game objects across the map
commands:
  placebuildings:
    aliases: [p]
    description: Place buildings according to set coordinates
    usage: Type /placebuildings
  testplacement:
    aliases: [c]
    description: Place an anvil in the map next to the players location
    usage: Type /testplacement
  testschematic:
    aliases: [s]
    description: Place a schematic in the map next to the players location
    usage: Type /testschematic