name: BlockSpawner
version: 0.1
main: plugin.CommandManager
description: Spawn obsidian blocks at set coordinates
commands:
  placeblocks:
    aliases: [p]
    description: Place obsidian blocks
    usage: Type /placeblocks
  testplacement:
    aliases: [c]
    description: Place a cow above player's heads
    usage: Type /testplacement